environment:
  matrix:
  - MSYSTEM: MINGW64
  TARGET: build\lean-3.2.1-windows.zip

install:
  - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -Syu" # update core
  - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -Su"  # update rest
  # upgrading gcc to 6.x fails
  - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -Suuy mingw-w64-x86_64-ninja mingw-w64-x86_64-cmake git"

build_script:
  - C:\msys64\usr\bin\bash -lc "exec 0</dev/null &&
      cd $APPVEYOR_BUILD_FOLDER;
      mkdir build && cd build;
      OPTIONS='';
      if [[ $APPVEYOR_REPO_BRANCH == master ]]; then OPTIONS+=' -DLEAN_VERSION_STRING=nightly'; export TARGET=build/lean-nightly-windows.zip; fi;
      cmake ../src -DINCLUDE_MSYS2_DLLS=ON -DCMAKE_BUILD_TYPE=Release $OPTIONS -G Ninja"
  - C:\msys64\usr\bin\bash -lc "exec 0</dev/null && cd $APPVEYOR_BUILD_FOLDER/build && ninja && cpack"

test_script:
  - C:\msys64\usr\bin\bash -lc "exec 0</dev/null && cd $APPVEYOR_BUILD_FOLDER/build && ctest -j4 --output-on-failure"

artifacts:
  - path: $TARGET
    name: binary

deploy:
  description: 'Lean release'
  provider: GitHub
  auth_token:
    secure: d+yPrDEAbiNrcf3a0PDNYEn/ieOOP6M7cP9zje+QkJEjHFdjBjWMe8b3qrC1hrus
  artifact: binary
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true
